-- =====================================================
-- mock_data.sql
-- Seed data for Job Tracker (users, jobs, saved_jobs, application_tracking)
-- Notes:
-- 1) Assumes empty tables (AUTO_INCREMENT starts at 1).
-- 2) All constraints are respected (FKs, uniques, checks).
-- Generated by AI.
-- =====================================================

USE careerforge;

START TRANSACTION;

-- ---------- USERS (6 total; >= 5 required) ----------
-- All users set as EMPLOYEE for simplicity; any user can be a job poster per schema.
INSERT INTO users
(username, email, password, first_name, last_name, user_type, is_active, company_name, location_address, lat, lon)
VALUES
    ('alex01',   'alex01@example.com',   '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.', 'Alex',   'Moore',   'EMPLOYEE', TRUE, NULL, 'Boston, MA',     42.3601, -71.0589),
    ('blair02',  'blair02@example.com',  '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.',  'Blair',  'Kim',     'EMPLOYEE', TRUE, NULL, 'New York, NY',   40.7128, -74.0060),
    ('casey03',  'casey03@example.com',  '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.', 'Casey',  'Lopez',   'EMPLOYEE', TRUE, NULL, 'Chicago, IL',    41.8781, -87.6298),
    ('devon04',  'devon04@example.com',  '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.', 'Devon',  'Singh',   'EMPLOYEE', TRUE, NULL, 'Austin, TX',     30.2672, -97.7431),
    ('elliot05', 'elliot05@example.com', '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.',   'Elliot', 'Zhang',   'EMPLOYEE', TRUE, NULL, 'Seattle, WA',    47.6062, -122.3321),
    ('finley06', 'finley06@example.com', '$2a$10$IDT1dc1cSOi54rg6.S26eeqIvTDA1Gs5ilDANEepOjr1X3PxMGoe.',  'Finley', 'Nguyen',  'EMPLOYEE', TRUE, NULL, 'San Jose, CA',   37.3382, -121.8863);

-- ---------- JOBS (30 total; >= 30 required) ----------
-- All jobs posted by user id 1 (Alex). Deadlines are in the future to satisfy chk_future_deadline.
-- Salaries are valid and min <= max. Required fields are non-empty.
INSERT INTO jobs
(posted_by, title, description, company, location, employment_type, salary_min, salary_max, requirements, benefits,
 created_at, updated_at, is_active, application_deadline, url, type, department, seniority, location_address, lat, lon)
VALUES
-- 1..10
(1, 'Software Engineer I',        'Build features in a cross-functional team.',      'Acme Corp',        'Boston, MA',   'FULL_TIME', 70000,  95000,  'Java, SQL',          'Health, 401k',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 30 DAY), 'https://acme.example/jobs/1', 'Engineering', 'Platform', 'Junior', '1 Main St, Boston, MA', 42.3601, -71.0589),
(1, 'Data Analyst',               'Analyze product metrics and dashboards.',         'Beta Analytics',   'New York, NY','FULL_TIME', 65000,  90000,  'SQL, Python, BI',    'Dental, PTO',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 35 DAY), 'https://beta.example/jobs/2', 'Analytics',  'BI',       'Junior', '200 Broadway, NY', 40.7128, -74.0060),
(1, 'Frontend Developer',         'React/Vite UI development.',                      'Gamma Labs',       'Chicago, IL', 'FULL_TIME', 75000, 105000,  'React, TS',          'Remote stipend',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 40 DAY), 'https://gamma.example/3',     'Engineering', 'Web',     'Mid',    '10 Loop, Chicago, IL', 41.8781, -87.6298),
(1, 'Backend Developer',          'Spring Boot services and APIs.',                  'Delta Systems',    'Austin, TX',  'FULL_TIME', 80000, 115000,  'Java, Spring',       'Stock options',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 28 DAY), 'https://delta.example/4',     'Engineering', 'Core',    'Mid',    '500 Tech Ave, Austin, TX', 30.2672, -97.7431),
(1, 'QA Engineer',                'Own test plans and automation.',                  'Epsilon Quality',  'Seattle, WA', 'FULL_TIME', 65000,  95000,  'Selenium/Jest',      'Parental leave',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 33 DAY), 'https://eps.example/5',       'Engineering', 'QA',      'Mid',    '9 Pike St, Seattle, WA', 47.6062, -122.3321),
(1, 'DevOps Engineer',            'CI/CD, IaC, observability.',                      'Zeta DevOps',      'San Jose, CA','FULL_TIME', 90000, 130000,  'AWS, Terraform',     'Education budget',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 45 DAY), 'https://zeta.example/6',      'Engineering', 'Ops',     'Mid',    '88 Cloud Rd, San Jose, CA', 37.3382, -121.8863),
(1, 'Product Manager',            'Own roadmap and prioritization.',                 'Eta Products',     'Boston, MA',  'FULL_TIME', 95000, 140000,  'Agile, Analytics',   'Bonus',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 42 DAY), 'https://eta.example/7',       'Product',     'Core',    'Mid',    '10 Beacon St, Boston, MA', 42.3584, -71.0598),
(1, 'UX Designer',                'Design flows and prototypes.',                    'Theta Design',     'New York, NY','FULL_TIME', 80000, 120000,  'Figma, Research',    'Wellness',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 37 DAY), 'https://theta.example/8',     'Design',      'UX',      'Mid',    '21 Madison Ave, NY', 40.7420, -73.9862),
(1, 'Data Engineer',              'ETL pipelines and warehousing.',                  'Iota Data',        'Chicago, IL', 'FULL_TIME', 90000, 130000,  'Spark, Airflow',     '401k match',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 38 DAY), 'https://iota.example/9',      'Engineering', 'Data',    'Mid',    '700 River Rd, Chicago, IL', 41.8818, -87.6232),
(1, 'Security Engineer',          'AppSec and threat modeling.',                     'Kappa Security',   'Austin, TX',  'FULL_TIME', 95000, 145000,  'OWASP, SAST',        'Home office',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 50 DAY), 'https://kappa.example/10',    'Engineering', 'Security','Senior', '77 Safe Dr, Austin, TX', 30.2711, -97.7437),

-- 11..20
(1, 'Mobile Developer (iOS)',     'SwiftUI apps.',                                   'Lambda Mobile',    'Seattle, WA', 'FULL_TIME', 85000, 125000,  'Swift, Xcode',       'Gym membership',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 31 DAY), 'https://lambda.example/11',   'Engineering', 'Mobile',  'Mid',    '1 Lake St, Seattle, WA', 47.6097, -122.3331),
(1, 'Mobile Developer (Android)', 'Android Kotlin apps.',                            'Mu Mobile',        'San Jose, CA','FULL_TIME', 85000, 125000,  'Kotlin, Gradle',     'Flexible PTO',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 29 DAY), 'https://mu.example/12',       'Engineering', 'Mobile',  'Mid',    '2 Orchard St, San Jose, CA', 37.3348, -121.8881),
(1, 'Site Reliability Engineer',  'Reliability and scaling.',                        'Nu Cloud',         'Boston, MA',  'FULL_TIME', 95000, 140000,  'K8s, Prometheus',    'On-call stipend',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 43 DAY), 'https://nu.example/13',       'Engineering', 'SRE',     'Mid',    '3 Harbor St, Boston, MA', 42.36, -71.06),
(1, 'Business Analyst',           'Requirements & process mapping.',                 'Xi Consulting',    'New York, NY','FULL_TIME', 70000, 100000,  'Jira, Visio',        'Transit pass',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 47 DAY), 'https://xi.example/14',       'Operations',  'Biz',     'Mid',    '4 Wall St, NY', 40.7060, -74.0086),
(1, 'Machine Learning Engineer',  'Train and deploy models.',                        'Omicron AI',       'Chicago, IL', 'FULL_TIME', 110000, 155000, 'PyTorch, MLOps',     'Research time',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 55 DAY), 'https://omicron.example/15',  'Engineering', 'AI',      'Senior', '5 AI Blvd, Chicago, IL', 41.88, -87.63),
(1, 'Technical Writer',           'Docs for devs and users.',                        'Pi Docs',          'Austin, TX',  'FULL_TIME', 65000,  90000,  'API docs, Markdown','Remote-first',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 27 DAY), 'https://pi.example/16',       'Docs',        'Tech',    'Mid',    '6 Pen St, Austin, TX', 30.26, -97.74),
(1, 'Customer Success Manager',   'Onboarding & retention.',                         'Rho Success',      'Seattle, WA', 'FULL_TIME', 65000,  95000,  'CRM, SQL basics',    'Commission',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 36 DAY), 'https://rho.example/17',      'Customer',    'CSM',     'Mid',    '7 Shoreline, Seattle, WA', 47.61, -122.33),
(1, 'IT Support Specialist',      'Tier-2 support.',                                 'Sigma IT',         'San Jose, CA','FULL_TIME', 55000,  80000,  'AD, Networking',     'Phone stipend',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 34 DAY), 'https://sigma.example/18',    'IT',          'Support', 'Junior', '8 Silicon Ave, San Jose, CA', 37.33, -121.89),
(1, 'HR Generalist',              'People ops and recruiting support.',              'Tau People',       'Boston, MA',  'FULL_TIME', 60000,  85000,  'HRIS, Compliance',   'Mental health',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 41 DAY), 'https://tau.example/19',      'HR',          'General', 'Mid',    '9 Beacon St, Boston, MA', 42.36, -71.06),
(1, 'Marketing Specialist',       'Campaigns & content.',                            'Upsilon Media',    'New York, NY','FULL_TIME', 60000,  90000,  'SEO, Analytics',     'Learning budget',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 39 DAY), 'https://ups.example/20',      'Marketing',   'Growth',  'Mid',    '10 Park Ave, NY', 40.75, -73.98),

-- 21..30
(1, 'Data Scientist',             'Experimentation and modeling.',                   'Phi Insights',     'Chicago, IL', 'FULL_TIME', 105000, 150000, 'Stats, Python',      'Conference',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 46 DAY), 'https://phi.example/21',      'Engineering', 'Data',    'Senior', '11 State St, Chicago, IL', 41.88, -87.63),
(1, 'Solutions Architect',        'Design scalable solutions.',                      'Chi Solutions',    'Austin, TX',  'FULL_TIME', 120000, 170000, 'Cloud, Architecture','Car allowance',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 44 DAY), 'https://chi.example/22',      'Engineering', 'PreSales','Senior', '12 Barton Springs, Austin, TX', 30.26, -97.75),
(1, 'Content Strategist',         'Editorial calendar & voice.',                     'Psi Content',      'Seattle, WA', 'FULL_TIME', 65000,  95000,  'CMS, Writing',       'Wellness',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 32 DAY), 'https://psi.example/23',      'Marketing',   'Content', 'Mid',    '13 Market St, Seattle, WA', 47.61, -122.33),
(1, 'Finance Analyst',            'FP&A and reporting.',                             'Omega Finance',    'San Jose, CA','FULL_TIME', 70000, 100000,  'Excel, SQL',         'Bonus',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 30 DAY), 'https://omega.example/24',    'Finance',     'FP&A',    'Mid',    '14 First St, San Jose, CA', 37.34, -121.89),
(1, 'Intern - Software',          'Summer internship in platform.',                  'Acme Corp',        'Boston, MA',  'INTERNSHIP', 0,     0,       'CS fundamentals',    'Mentorship',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 60 DAY), 'https://acme.example/25',     'Engineering', 'Platform','Intern', '1 Main St, Boston, MA', 42.36, -71.06),
(1, 'Contract UI Developer',      'Short-term React work.',                          'Gamma Labs',       'Chicago, IL', 'CONTRACT',  60.00,  90.00,  'React, HTML/CSS',    'N/A',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 25 DAY), 'https://gamma.example/26',    'Engineering', 'Web',     'Mid',    '10 Loop, Chicago, IL', 41.88, -87.63),
(1, 'Remote Support Engineer',    'Fully-remote L2 support.',                        'Sigma IT',         'Remote',      'REMOTE',    55000,  85000,  'Linux, Scripting',   'Home office',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 52 DAY), 'https://sigma.example/27',    'IT',          'Support', 'Mid',    'Remote', NULL, NULL),
(1, 'Part-time QA Tester',        'Weekend testing coverage.',                       'Epsilon Quality',  'Seattle, WA', 'PART_TIME', 25.00,  40.00,  'Manual testing',     'N/A',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 26 DAY), 'https://eps.example/28',      'Engineering', 'QA',      'Junior', '9 Pike St, Seattle, WA', 47.61, -122.33),
(1, 'Solutions Consultant',       'Discovery & demos.',                              'Chi Solutions',    'Austin, TX',  'FULL_TIME', 100000, 140000, 'PreSales, Cloud',    'Commission',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 49 DAY), 'https://chi.example/29',      'Sales',       'Solutions','Mid',   '12 Barton Springs, Austin, TX', 30.26, -97.75),
(1, 'Research Scientist (AI)',    'Foundation model research.',                      'Omicron AI',       'Chicago, IL', 'FULL_TIME', 140000, 200000, 'DL, LLMs',           'Publications support',
 NOW(), NOW(), TRUE, DATE_ADD(NOW(), INTERVAL 58 DAY), 'https://omicron.example/30',  'Engineering', 'AI',      'Senior', '5 AI Blvd, Chicago, IL', 41.88, -87.63);

-- ---------- SAVED JOBS ----------
-- Each user saves 5 jobs; choose disjoint 5-job windows to avoid unique collisions.
-- User 1 saves jobs 1-5, User 2 saves 6-10, ..., User 6 saves 26-30.
INSERT INTO saved_jobs (user_id, job_id, created_at) VALUES
                                                         (1,  1, NOW()), (1,  2, NOW()), (1,  3, NOW()), (1,  4, NOW()), (1,  5, NOW()),
                                                         (2,  6, NOW()), (2,  7, NOW()), (2,  8, NOW()), (2,  9, NOW()), (2, 10, NOW()),
                                                         (3, 11, NOW()), (3, 12, NOW()), (3, 13, NOW()), (3, 14, NOW()), (3, 15, NOW()),
                                                         (4, 16, NOW()), (4, 17, NOW()), (4, 18, NOW()), (4, 19, NOW()), (4, 20, NOW()),
                                                         (5, 21, NOW()), (5, 22, NOW()), (5, 23, NOW()), (5, 24, NOW()), (5, 25, NOW()),
                                                         (6, 26, NOW()), (6, 27, NOW()), (6, 28, NOW()), (6, 29, NOW()), (6, 30, NOW());

-- ---------- APPLICATIONS ----------
-- Each user applies to 5 jobs; mirrors the saved sets for simplicity.
-- Status kept as 'APPLIED' so interview/follow-up dates can remain NULL (satisfy future-date checks).
INSERT INTO application_tracking
(applicant, job, application_status, applied_date, last_updated, notes, resume_path, cover_letter, interview_date, follow_up_date)
VALUES
    (1,  1, 'APPLIED', NOW(), NOW(), 'Initial application.',        '/resumes/u1.pdf',  NULL, NULL, NULL),
    (1,  2, 'APPLIED', NOW(), NOW(), 'Initial application.',        '/resumes/u1.pdf',  NULL, NULL, NULL),
    (1,  3, 'APPLIED', NOW(), NOW(), 'Initial application.',        '/resumes/u1.pdf',  NULL, NULL, NULL),
    (1,  4, 'APPLIED', NOW(), NOW(), 'Initial application.',        '/resumes/u1.pdf',  NULL, NULL, NULL),
    (1,  5, 'APPLIED', NOW(), NOW(), 'Initial application.',        '/resumes/u1.pdf',  NULL, NULL, NULL),

    (2,  6, 'APPLIED', NOW(), NOW(), 'Submitted via portal.',       '/resumes/u2.pdf',  NULL, NULL, NULL),
    (2,  7, 'APPLIED', NOW(), NOW(), 'Submitted via portal.',       '/resumes/u2.pdf',  NULL, NULL, NULL),
    (2,  8, 'APPLIED', NOW(), NOW(), 'Submitted via portal.',       '/resumes/u2.pdf',  NULL, NULL, NULL),
    (2,  9, 'APPLIED', NOW(), NOW(), 'Submitted via portal.',       '/resumes/u2.pdf',  NULL, NULL, NULL),
    (2, 10, 'APPLIED', NOW(), NOW(), 'Submitted via portal.',       '/resumes/u2.pdf',  NULL, NULL, NULL),

    (3, 11, 'APPLIED', NOW(), NOW(), 'Referred by friend.',         '/resumes/u3.pdf',  NULL, NULL, NULL),
    (3, 12, 'APPLIED', NOW(), NOW(), 'Referred by friend.',         '/resumes/u3.pdf',  NULL, NULL, NULL),
    (3, 13, 'APPLIED', NOW(), NOW(), 'Referred by friend.',         '/resumes/u3.pdf',  NULL, NULL, NULL),
    (3, 14, 'APPLIED', NOW(), NOW(), 'Referred by friend.',         '/resumes/u3.pdf',  NULL, NULL, NULL),
    (3, 15, 'APPLIED', NOW(), NOW(), 'Referred by friend.',         '/resumes/u3.pdf',  NULL, NULL, NULL),

    (4, 16, 'APPLIED', NOW(), NOW(), 'Cold application.',           '/resumes/u4.pdf',  NULL, NULL, NULL),
    (4, 17, 'APPLIED', NOW(), NOW(), 'Cold application.',           '/resumes/u4.pdf',  NULL, NULL, NULL),
    (4, 18, 'APPLIED', NOW(), NOW(), 'Cold application.',           '/resumes/u4.pdf',  NULL, NULL, NULL),
    (4, 19, 'APPLIED', NOW(), NOW(), 'Cold application.',           '/resumes/u4.pdf',  NULL, NULL, NULL),
    (4, 20, 'APPLIED', NOW(), NOW(), 'Cold application.',           '/resumes/u4.pdf',  NULL, NULL, NULL),

    (5, 21, 'APPLIED', NOW(), NOW(), 'Applied with tailored CV.',   '/resumes/u5.pdf',  NULL, NULL, NULL),
    (5, 22, 'APPLIED', NOW(), NOW(), 'Applied with tailored CV.',   '/resumes/u5.pdf',  NULL, NULL, NULL),
    (5, 23, 'APPLIED', NOW(), NOW(), 'Applied with tailored CV.',   '/resumes/u5.pdf',  NULL, NULL, NULL),
    (5, 24, 'APPLIED', NOW(), NOW(), 'Applied with tailored CV.',   '/resumes/u5.pdf',  NULL, NULL, NULL),
    (5, 25, 'APPLIED', NOW(), NOW(), 'Applied with tailored CV.',   '/resumes/u5.pdf',  NULL, NULL, NULL),

    (6, 26, 'APPLIED', NOW(), NOW(), 'Applied via LinkedIn.',       '/resumes/u6.pdf',  NULL, NULL, NULL),
    (6, 27, 'APPLIED', NOW(), NOW(), 'Applied via LinkedIn.',       '/resumes/u6.pdf',  NULL, NULL, NULL),
    (6, 28, 'APPLIED', NOW(), NOW(), 'Applied via LinkedIn.',       '/resumes/u6.pdf',  NULL, NULL, NULL),
    (6, 29, 'APPLIED', NOW(), NOW(), 'Applied via LinkedIn.',       '/resumes/u6.pdf',  NULL, NULL, NULL),
    (6, 30, 'APPLIED', NOW(), NOW(), 'Applied via LinkedIn.',       '/resumes/u6.pdf',  NULL, NULL, NULL);

COMMIT;

-- =====================================================
-- Verification tips (optional):
-- SELECT COUNT(*) FROM users;                    -- expect 6
-- SELECT COUNT(*) FROM jobs;                     -- expect 30
-- SELECT user_id, COUNT(*) FROM saved_jobs GROUP BY user_id;         -- each = 5
-- SELECT applicant, COUNT(*) FROM application_tracking GROUP BY applicant; -- each = 5
-- =====================================================
